rails/webInterface/config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  resources :entries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/webInterface/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/webInterface/app/models/entry.rb
class Entry < ApplicationRecord
    # for filtering out lower confidence entries
    scope :above80, -> {where("confidenceVal >= 80")}

    # Search by License Plate
    def self.searchLP(searchLP)
        if searchLP == ""
            return where(nil)
        end
        searchLP = "%" + searchLP + "%"
        where("LP LIKE ?", searchLP)
    end

    # Search by Date
    def self.searchDate(searchDate) # YYYY-MM-DD
        #formatting input
        if searchDate == ""
            return where(nil)
        end
        formattedDate = DateTime.parse(searchDate.to_s)
        formattedDate = formattedDate.change(:offset => "-0700")
        formattedDate = formattedDate.change(:hour => 0).change(:min => 0).change(:sec => 0)

        timeSinceEpoch = formattedDate.to_datetime.strftime("%Q").to_i

        oneDayLater = (timeSinceEpoch + (1000 * 60 *60 * 24)).to_i

        where("unixTime >= ? AND unixTime <= ?", timeSinceEpoch, oneDayLater)
    end
end

rails/webInterface/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/webInterface/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index

    # for searching using search fields 
    if params[:searchLP]
      @entries = Entry.searchLP(params[:searchLP])
    
    elsif params[:searchDate]
      @entries = Entry.searchDate(params[:searchDate])
    
    else
      @entries = Entry.where(nil)
    end

    # if there are no matching entries with confidenceVal > 80, display matching entries with confidenceVal < 80
    @aboveThreshold = @entries.above80()
    if @aboveThreshold.any?
      @entries = @aboveThreshold
    end

  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # These functions have been left in case any RESTful actions are wanted.

  # GET /entries/new
  # def new
  #   @entry = Entry.new
  # end

  # GET /entries/1/edit
  # def edit
  # end

  # POST /entries
  # POST /entries.json
  # def create
  #   @entry = Entry.new(entry_params)

  #   respond_to do |format|
  #     if @entry.save
  #       format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
  #       format.json { render :show, status: :created, location: @entry }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  # def update
  #   respond_to do |format|
  #     if @entry.update(entry_params)
  #       format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @entry }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /entries/1
  # DELETE /entries/1.json
  # def destroy
  #   @entry.destroy
  #   respond_to do |format|
  #     format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:LP, :confidenceVal, :unixTime, :siteName, :cameraID)
    end
end

rails/webInterface/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/webInterface/app/helpers/entries_helper.rb
module EntriesHelper
end

rails/webInterface/app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :LP %>
    <%= form.text_area :LP %>
  </div>

  <div class="field">
    <%= form.label :confidenceVal %>
    <%= form.text_field :confidenceVal %>
  </div>

  <div class="field">
    <%= form.label :unixTime %>
    <%= form.text_field :unixTime %>
  </div>

  <div class="field">
    <%= form.label :jpgLink %>
    <%= form.text_area :jpgLink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/webInterface/app/views/entries/edit.html.erb
<h1>Editing Entry</h1>
<!-- 
<%= # render 'form', entry: @entry %>
 -->
<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

rails/webInterface/app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Entries</h2>
<h3>(Most Recent First)</h3>

<% if @entries.blank? %>
<h2>There are no entries containing your term.</h2>

<% else %>
  <table>
    <thead>
      <tr>
        <th> License Plate </th>
        <th> Confidence Value </th>
        <th> Date & Time </th>
        <th> Location </th>
        <th> Camera ID </th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @entries.reverse.each do |entry| %>
        <tr>
          <td><%= entry.LP %></td>
          <td><%= entry.confidenceVal %></td>
          <td><%= (Time.strptime(entry.unixTime.to_s, '%Q').strftime("%Y-%m-%d %k:%M:%S.%L")).to_s %></td>
          <td><%= entry.siteName %></td>
          <td><%= entry.cameraID %></td>
          <td><%= link_to 'Details', entry %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end %>

rails/webInterface/app/views/entries/new.html.erb
<h1>New Entry</h1>
<!-- 
<%= # render 'form', entry: @entry %>
 -->
<%= link_to 'Back', entries_path %>

rails/webInterface/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Details</h2>

<p>
  <strong>License Plate:</strong>
  <%= @entry.LP %>
</p>

<p>
  <strong>Confidence Value:</strong>
  <%= @entry.confidenceVal %>
</p>

<p>
  <strong>Date & Time:</strong>
  <%= (Time.strptime(@entry.unixTime.to_s, '%Q').strftime("%Y-%m-%d %k:%M:%S.%L")).to_s %>
</p>

<p>
    <strong>Location:</strong>
    <%= @entry.siteName %>
</p>

<p>
    <strong>Camera ID:</strong>
    <%= @entry.cameraID %>
</p>

<p>
  <strong>Jpglink:</strong>
  <%= image_tag @entry.siteName+"-cam"+@entry.cameraID.to_s+"-"+@entry.unixTime.to_s %>
</p>

<%= link_to 'Back to List', entries_path %>

rails/webInterface/app/views/layouts/application.html.erb
<link href="http://fonts.googleapis.com/css?family=Quicksand:400,700" rel="stylesheet" type="text/css" />
<!DOCTYPE html>
<html>
  <head>
    <title>WebInterface</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <h1>LP Database</h1>

  <h2>Search</h2>

    <%= form_tag(entries_path, :method => 'get', id: 'lp-search-form') do %>
      <strong> Partial LP:</strong> <%= text_field_tag :searchLP, params[:searchLP], placeholder: 'Plate Number' %>
      <%= submit_tag 'Search', :name => nil %>

    <% end %>

    <%= form_tag(entries_path, :method => 'get', id: 'date-search-form') do %>
      <strong> On Day:</strong> <%= text_field_tag :searchDate, params[:searchDate], placeholder: 'yyyy-mm-dd' %>
      <%= submit_tag 'Search', :name => nil %>

    <% end %>

    <strong><%= link_to 'Back to List', entries_path %></strong>

  <body>
    <body class="skins-air">
    <%= yield %>
  </body>

  
</html>